#!/bin/sh
cat << __EOC__
$ ./configure  '--prefix=/opt/bacula/' '--with-postgresql=/usr/pgsql-9.5/'

Configuration on Wed Oct 19 14:14:22 BRT 2016:

   Host:		     x86_64-unknown-linux-gnu -- redhat 
   Bacula version:	     Bacula 7.4.3 (18 June 2016)
   Source code location:     .
   Install binaries:	     /opt/bacula/sbin
   Install libraries:	     /opt/bacula/lib
   Install config files:     /opt/bacula/etc
   Scripts directory:	     /opt/bacula/etc
   Archive directory:	     /tmp
   Working directory:	     /opt/bacula/working
   PID directory:	     /var/run
   Subsys directory:	     /var/lock/subsys
   Man directory:	     ${datarootdir}/man
   Data directory:	     /opt/bacula/share
   Plugin directory:	     /opt/bacula/lib
   C Compiler:		     gcc 4.4.7
   C++ Compiler:	     /usr/bin/g++ 4.4.7
   Compiler flags:	      -g -O2 -Wall -x c++ -fno-strict-aliasing -fno-exceptions -fno-rtti
   Linker flags:	      
   Libraries:		     -lpthread -ldl -ldl 
   Statically Linked Tools:  no
   Statically Linked FD:     no
   Statically Linked SD:     no
   Statically Linked DIR:    no
   Statically Linked CONS:   no
   Database backends:	     PostgreSQL
   Database port:	      
   Database name:	     bacula
   Database user:	     bacula
   Database SSL options:     

   Job Output Email:	     root@localhost
   Traceback Email:	     root@localhost
   SMTP Host Address:	     localhost

   Director Port:	     9101
   File daemon Port:	     9102
   Storage daemon Port:      9103

   Director User:	     
   Director Group:	     
   Storage Daemon User:      
   Storage DaemonGroup:      
   File Daemon User:	     
   File Daemon Group:	     

   Large file support:	     yes
   Bacula conio support:     yes -ltinfo
   readline support:	     no 
   TCP Wrappers support:     no 
   TLS support: 	     yes
   Encryption support:	     yes
   ZLIB support:	     yes
   LZO support: 	     no
   enable-smartalloc:	     yes
   enable-lockmgr:	     no
   bat support: 	     no
   client-only: 	     no
   build-dird:		     yes
   build-stored:	     yes
   Plugin support:	     yes
   AFS support: 	     no
   ACL support: 	     no
   XATTR support:	     yes
   systemd support:	     no 
   Batch insert enabled:     PostgreSQL

  
__EOC__
